blank_issues_enabled: false
contact_links:
  - name: 📖 Guia de Contribuição
    url: https://github.com/brenohp/mural-de-aprendizagem/blob/main/CONTRIBUTING.md
    about: Por favor, leia nosso guia antes de criar uma issue ou contribuir.
