# Nome do workflow de teste
name: Teste de Diagnóstico da Pipeline

# Gatilhos: push na main e também um gatilho manual
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite que você rode o workflow manualmente na aba "Actions"

# Apenas uma tarefa
jobs:
  teste:
    # Nome da tarefa
    name: Teste Mínimo
    # Máquina virtual
    runs-on: ubuntu-latest

    # Passos
    steps:
      # Este é o passo mais básico e fundamental de qualquer workflow.
      # Ele usa uma action oficial do GitHub para baixar o código.
      - name: 1. Testando o checkout de código
        uses: actions/checkout@v4

      # Este passo simplesmente executa um comando no terminal da máquina virtual
      # para listar os arquivos que foram baixados.
      - name: 2. Listando arquivos no diretório
        run: ls -l