# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Pipeline de Verificação e Qualidade

# Define os gatilhos: quando esta automação deve rodar
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Define as tarefas (jobs) que serão executadas
jobs:
  verificacao:
    name: Verificação de Qualidade
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Baixa o código do seu repositório
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Valida o HTML usando a action e a VERSÃO CORRETA da documentação
      - name: 2. Validar sintaxe do HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          # O parâmetro 'root' aponta para o diretório a ser verificado.
          # './' significa a raiz do nosso projeto.
          root: ./

      # Passo 2.1: Salva o arquivo de log da validação
      # Como sugerido na documentação, este passo salva o log como um "artefato".
      # Você poderá baixá-lo na página da Action que rodou.
      - name: 2.1 Salvar log de validação HTML
        uses: actions/upload-artifact@v4
        with:
          name: log-validacao-html
          path: log.log

      # Passo 3: Verifica se existem links quebrados no seu site
      - name: 3. Verificar links quebrados
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose

      # Passo 4: Verifica a formatação do código com Prettier
      - name: 4. Verificar formatação do código
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .